# Generated by Django 5.2.1 on 2025-09-06 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_precio_compra_to_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Quíntuple, Antirrábica', max_length=100)),
                ('especies', models.JSONField(default=list, help_text="Especies aplicables: ['Perro', 'Gato']")),
                ('frecuencia_meses', models.IntegerField(help_text='Frecuencia en meses para refuerzo')),
                ('es_obligatoria', models.BooleanField(default=True, help_text='¿Es obligatoria por ley peruana?')),
                ('edad_minima_semanas', models.IntegerField(default=6, help_text='Edad mínima en semanas para primera aplicación')),
                ('enfermedad_previene', models.TextField(help_text='Enfermedades que previene')),
                ('dosis_total', models.IntegerField(default=1, help_text='Número total de dosis en el protocolo inicial')),
                ('intervalo_dosis_semanas', models.IntegerField(default=3, help_text='Semanas entre dosis del protocolo inicial')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('vacuna', 'Vacunación'), ('desparasitacion_interna', 'Desparasitación Interna'), ('desparasitacion_externa', 'Desparasitación Externa'), ('control_general', 'Control General'), ('tratamiento', 'Tratamiento Específico'), ('cirugia', 'Cirugía'), ('emergencia', 'Emergencia'), ('revision', 'Revisión de Rutina')], default='control_general', max_length=30)),
                ('motivo_consulta', models.TextField(help_text='Motivo de la consulta')),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico del veterinario')),
                ('tratamiento_aplicado', models.TextField(blank=True, help_text='Tratamiento o procedimiento realizado')),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos recetados')),
                ('proxima_cita', models.DateField(blank=True, help_text='Fecha recomendada para próxima cita', null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Peso registrado durante la consulta', max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal en °C', max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('adjuntos', models.JSONField(blank=True, default=list, help_text='URLs de archivos adjuntos (radiografías, análisis, etc.)')),
                ('cita', models.ForeignKey(blank=True, help_text='Cita asociada a este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cita')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='api.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_realizadas', to='api.veterinario')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialVacunacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_aplicacion', models.DateField(help_text='Fecha real de aplicación')),
                ('proxima_fecha', models.DateField(help_text='Próxima fecha calculada automáticamente')),
                ('lote', models.CharField(blank=True, help_text='Lote de la vacuna aplicada', max_length=50)),
                ('laboratorio', models.CharField(blank=True, help_text='Laboratorio fabricante', max_length=100)),
                ('dosis_numero', models.IntegerField(default=1, help_text='Número de dosis en el protocolo (1ra, 2da, etc.)')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del veterinario')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('proxima', 'Próxima'), ('aplicada', 'Aplicada')], default='aplicada', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(blank=True, help_text='Cita en la que se aplicó la vacuna', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cita')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_vacunacion', to='api.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_aplicadas', to='api.veterinario')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='api.vacuna')),
            ],
            options={
                'verbose_name': 'Historial de Vacunación',
                'verbose_name_plural': 'Historiales de Vacunación',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
