# Generated by Django 5.2.1 on 2025-09-07 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vacuna_historialmedico_historialvacunacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='producto_inventario',
            field=models.ForeignKey(blank=True, help_text='Relación con el producto en inventario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto'),
        ),
    ]
