# Generated by Django 5.2.1 on 2025-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vacuna_producto_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacunacion',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('proxima', 'Próxima'), ('aplicada', 'Aplicada'), ('completado', 'Completado')], default='aplicada', max_length=20),
        ),
    ]
