# Generated by Django 5.2.1 on 2025-09-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_create_default_external_veterinarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='max_dias_atraso',
            field=models.IntegerField(default=14, help_text='Días máximos de atraso antes de reiniciar protocolo'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='protocolo_cachorro',
            field=models.JSONField(blank=True, default=dict, help_text="Protocolo especial para cachorros: {'dosis_total': 4, 'intervalos': [3, 3, 4]} - Si está vacío, usa protocolo estándar"),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='protocolo_dosis',
            field=models.JSONField(blank=True, default=list, help_text="Protocolo detallado: [{'dosis': 1, 'semanas_siguiente': 3}, {'dosis': 2, 'semanas_siguiente': 4}] - Si está vacío, usa dosis_total e intervalo_dosis_semanas"),
        ),
    ]
