# Generated by Django 5.2.1 on 2025-09-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_advanced_vaccination_protocol_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacunacion',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('proxima', 'Próxima'), ('aplicada', 'Aplicada'), ('completado', 'Completado'), ('vencida_reinicio', 'Vencida - Protocolo Reiniciado')], default='aplicada', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mascota',
            unique_together={('nombreMascota', 'responsable')},
        ),
    ]
