# Generated by Django 5.2.1 on 2025-09-16 22:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_mascota_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(max_length=50, validators=[api.models.validate_safe_name]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=100, validators=[api.models.validate_safe_name]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombreMascota',
            field=models.CharField(max_length=50, validators=[api.models.validate_safe_name]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100, validators=[api.models.validate_safe_name]),
        ),
    ]
