# Generated by Django 5.2.1 on 2025-09-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_mascota_color_alter_mascota_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialvacunacion',
            name='fecha_aplicacion',
            field=models.DateField(blank=True, help_text='Fecha real de aplicación (NULL para dosis pendientes)', null=True),
        ),
    ]
