# Generated by Django 5.2.1 on 2025-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_allow_null_fecha_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email del responsable', max_length=254, null=True, unique=True),
        ),
    ]
