# Generated by Django 5.2.1 on 2025-09-25 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_email_to_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Consulta General, Cirugía, Emergencia', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de cita')),
                ('duracion_minutos', models.IntegerField(default=30, help_text='Duración estimada en minutos')),
                ('tiempo_preparacion', models.IntegerField(default=5, help_text='Tiempo previo necesario para preparar (minutos)')),
                ('tiempo_limpieza', models.IntegerField(default=10, help_text='Tiempo posterior necesario para limpieza (minutos)')),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente'), (5, 'Crítica/Emergencia')], default=1, help_text='Prioridad del tipo de cita')),
                ('color', models.CharField(default='#3498db', help_text='Color hexadecimal para mostrar en calendario', max_length=7)),
                ('requiere_consultorio_especial', models.BooleanField(default=False, help_text='¿Requiere un consultorio específico?')),
                ('permite_overlap', models.BooleanField(default=False, help_text='¿Permite solapamiento con otras citas?')),
                ('costo_base', models.DecimalField(blank=True, decimal_places=2, help_text='Costo base estimado del tipo de cita', max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cita',
                'verbose_name_plural': 'Tipos de Cita',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de jornada')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de jornada')),
                ('tiene_descanso', models.BooleanField(default=False, help_text='¿Tiene descanso durante la jornada?')),
                ('hora_inicio_descanso', models.TimeField(blank=True, help_text='Hora de inicio del descanso', null=True)),
                ('hora_fin_descanso', models.TimeField(blank=True, help_text='Hora de fin del descanso', null=True)),
                ('activo', models.BooleanField(default=True, help_text='¿Este horario está actualmente activo?')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, help_text='Fecha desde la cual es válido este horario', null=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Fecha hasta la cual es válido este horario', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabajo', to='api.veterinario')),
            ],
            options={
                'verbose_name': 'Horario de Trabajo',
                'verbose_name_plural': 'Horarios de Trabajo',
                'ordering': ['veterinario', 'dia_semana'],
                'unique_together': {('veterinario', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='SlotTiempo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_minutos', models.IntegerField(help_text='Duración calculada en minutos')),
                ('disponible', models.BooleanField(default=True)),
                ('motivo_no_disponible', models.CharField(blank=True, choices=[('ocupado', 'Slot ocupado'), ('descanso', 'Tiempo de descanso'), ('mantenimiento', 'Mantenimiento de consultorio'), ('emergencia', 'Reservado para emergencias'), ('personal', 'Tiempo personal del veterinario'), ('otro', 'Otro motivo')], max_length=200)),
                ('permite_emergencias', models.BooleanField(default=True, help_text='¿Este slot puede ser usado para emergencias?')),
                ('reservado_hasta', models.DateTimeField(blank=True, help_text='Tiempo límite de reserva temporal (para evitar doble booking)', null=True)),
                ('generado_automaticamente', models.BooleanField(default=True, help_text='¿Este slot fue generado automáticamente?')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots_tiempo', to='api.consultorio')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_tiempo', to='api.veterinario')),
                ('tipo_cita_permitida', models.ForeignKey(blank=True, help_text='Si se especifica, solo permite este tipo de cita', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipocita')),
            ],
            options={
                'verbose_name': 'Slot de Tiempo',
                'verbose_name_plural': 'Slots de Tiempo',
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['fecha', 'disponible'], name='api_slottie_fecha_5eea1d_idx'), models.Index(fields=['veterinario', 'fecha'], name='api_slottie_veterin_aa5a9d_idx')],
                'unique_together': {('veterinario', 'consultorio', 'fecha', 'hora_inicio')},
            },
        ),
    ]
