# Generated by Django 5.2.1 on 2025-09-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tipocita_horariotrabajo_slottiempo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='color',
            field=models.CharField(default='#3498db', help_text='Color hexadecimal para mostrar en calendario', max_length=7),
        ),
        migrations.AddField(
            model_name='servicio',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.IntegerField(default=30, help_text='Duración estimada en minutos'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='permite_overlap',
            field=models.BooleanField(default=False, help_text='Si permite solapamiento con otras citas'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente'), (5, 'Crítica/Emergencia')], default=2, help_text='Nivel de prioridad del servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='requiere_consultorio_especial',
            field=models.BooleanField(default=False, help_text='Si requiere un consultorio específico (cirugías, etc.)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tiempo_limpieza',
            field=models.IntegerField(default=10, help_text='Tiempo posterior necesario para limpieza (minutos)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tiempo_preparacion',
            field=models.IntegerField(default=5, help_text='Tiempo previo necesario para preparar (minutos)'),
        ),
    ]
