# Generated by Django 5.2.1 on 2025-09-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_servicio_options_servicio_actualizado_and_more'),
    ]

    operations = [
        # Primero eliminar el campo que referencia TipoCita
        migrations.RemoveField(
            model_name='slottiempo',
            name='tipo_cita_permitida',
        ),
        # Agregar el nuevo campo que referencia Servicio
        migrations.AddField(
            model_name='slottiempo',
            name='servicio_permitido',
            field=models.ForeignKey(
                blank=True,
                help_text='Si se especifica, solo permite este tipo de servicio',
                null=True,
                on_delete=models.SET_NULL,
                to='api.servicio'
            ),
        ),
        # Finalmente eliminar el modelo TipoCita
        migrations.DeleteModel(
            name='TipoCita',
        ),
    ]
