# Generated by Django 5.2.1 on 2025-09-25 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20250924_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('CONSULTA', 'Consulta Médica'), ('BAÑADO', 'Servicios de Baño'), ('VACUNACION', 'Vacunación'), ('CIRUGIA', 'Cirugía'), ('EMERGENCIA', 'Emergencia')], default='CONSULTA', help_text='Categoría del servicio para flujo específico', max_length=20),
        ),
        migrations.CreateModel(
            name='DetalleCompletarCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicaciones_bañado', models.TextField(blank=True, help_text='Indicaciones especiales para el baño')),
                ('tipo_pelaje', models.CharField(blank=True, help_text='Tipo de pelaje de la mascota', max_length=50)),
                ('productos_especiales', models.TextField(blank=True, help_text='Productos especiales utilizados')),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico médico')),
                ('tratamiento_recomendado', models.TextField(blank=True, help_text='Tratamiento recomendado')),
                ('observaciones_medicas', models.TextField(blank=True, help_text='Observaciones médicas generales')),
                ('proxima_cita_sugerida', models.DateField(blank=True, help_text='Próxima cita sugerida', null=True)),
                ('observaciones_vacunacion', models.TextField(blank=True, help_text='Observaciones sobre vacunación')),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_productos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completado', models.BooleanField(default=False)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='api.cita')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veterinario')),
            ],
            options={
                'verbose_name': 'Detalle de Cita',
                'verbose_name_plural': 'Detalles de Citas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='api.cita')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
                'ordering': ['-creado'],
            },
        ),
    ]
