# Generated by Django 5.2.1 on 2025-10-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_servicio_categoria_detallecompletarcita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slottiempo',
            name='duracion_minutos',
            field=models.IntegerField(default=30, help_text='Duración calculada en minutos'),
        ),
    ]
