# Generated by Django 5.2.1 on 2025-10-06 20:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_datos_iniciales_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('recepcionista', 'Recepcionista'), ('veterinario', 'Veterinario'), ('veterinario_externo', 'Veterinario Externo'), ('Responsable', 'Responsable/Dueño'), ('inventario', 'Inventario'), ('administrador', 'Administrador')], help_text='Rol al que se aplica este permiso', max_length=50)),
                ('modulo', models.CharField(help_text='Módulo del sistema (dashboard, citas, mascotas, etc.)', max_length=50)),
                ('permisos', models.JSONField(default=dict, help_text="Permisos del módulo: {'ver': True, 'crear': False, 'editar': True, ...}")),
                ('descripcion_modulo', models.CharField(blank=True, help_text='Descripción del módulo para mostrar en la UI', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso por Rol',
                'verbose_name_plural': 'Permisos por Rol',
                'ordering': ['rol', 'modulo'],
                'unique_together': {('rol', 'modulo')},
            },
        ),
    ]
