# Generated by Django 5.2.1 on 2025-10-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_sistema_permisos_dinamico'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('veterinario', 'fecha', 'hora'), name='unique_cita_veterinario_fecha_hora', violation_error_message='El veterinario ya tiene una cita agendada en esta fecha y hora.'),
        ),
    ]
