# Generated by Django 5.2.1 on 2026-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_redundant_email_and_add_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='edad_maxima_semanas',
            field=models.IntegerField(blank=True, help_text='Edad máxima en semanas (opcional, dejar vacío si no aplica)', null=True),
        ),
    ]
